AG-6686 - Allow configuration of axis title spacing and set theme def…
ag-grid/ag-charts pull request #253
Opened 2023-09-21 14:53 UTC by manapeirov

PR for https://ag-grid.atlassian.net/browse/AG-6686

2023-09-22 14:59 UTC, markdurrant approved these changes
All LGTM 👍

2023-09-25 06:56 UTC, alantreadway requested changes
Code changes LGTM, please update snapshots.

2023-09-25 11:33 UTC, manapeirov commented
@alantreadway PTAL

2023-09-25 11:56 UTC, alantreadway commented on packages/ag-charts-community/src/chart/__image_snapshots__/cartesian-chart-test-ts-cartesian-chart-series-highlighting-should-correctly-change-highlighting-state-and-reset-1-snap.png
This doesn't look right to me?

2023-09-25 11:56 UTC, alantreadway commented on packages/ag-charts-community/src/chart/series/__image_snapshots__/series-labels-test-ts-series-labels-create-for-area-column-combo-series-labels-it-should-render-to-canvas-as-expected-1-snap.png
Ditto

2023-09-25 15:43 UTC, alantreadway approved these changes
LGTM

2023-09-25 15:43 UTC, merged