AG-12522 - Fix firing of click event after drag.
ag-grid/ag-charts pull request #2743
Opened 2024-10-15 13:47 UTC by alantreadway

2024-10-15 14:46 UTC, olegat requested changes
> [!CAUTION]
> This solution is not compliant with WCAG 2 Success Criteria 2.2.3:
> > 2.2.3 No Timing, Level AAA
> > Timing is not an essential part of the event or activity presented by the content, except for non-interactive synchronized media and real-time events.
> https://www.w3.org/WAI/WCAG22/quickref/?versions=2.1#no-timing

As we discussed on Slack, another solution could be to record `mousemove` events in `InteractionManager` as we do with `mousedown` and `mouseup` events. AFAICT, this approach would be compliant with WCAG 2. Are there any side-effects from this approach that I am unaware of?

2024-10-16 09:21 UTC, olegat requested changes
[deleted]

2024-10-16 09:45 UTC, alantreadway commented
> Would it be better to merge this breaking change `next` rather than `latest`?

We don't document the expected type of `event`, so although it is a change in behaviour, it is still correct from an API/contract perspective.

2024-10-16 10:22 UTC, olegat commented on packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                return this.recordUp(event) ? 'drag-end' : 'click';
test

2024-10-16 10:23 UTC, olegat approved these changes
LGTM

2024-10-16 10:23 UTC, merged