Refactor RadialBarSeries animations to use `fromToMotion`.
ag-grid/ag-charts pull request #305
Opened 2023-10-03 15:32 UTC by alantreadway

Bonus:
- Improve bar-like cases.

2023-10-03 15:38 UTC, lsjroberts commented on packages/ag-charts-enterprise/src/series/radial-bar/__image_snapshots__/__diff_output__/radial-bar-test-ts-radial-bar-chart-initial-animation-for-example-options-should-animate-at-25-1-snap-diff.png
👀

2023-10-03 15:40 UTC, lsjroberts requested changes
some diffs to remove

2023-10-03 15:54 UTC, alantreadway commented on packages/ag-charts-enterprise/src/series/radial-bar/__image_snapshots__/__diff_output__/radial-bar-test-ts-radial-bar-chart-initial-animation-for-example-options-should-animate-at-25-1-snap-diff.png
Fixed:
1) Reason for diff is that there was no easing function previously.
2) I've removed the diffs here - apologies.

2023-10-03 15:54 UTC, lsjroberts approved these changes

2023-10-04 10:00 UTC, merged

2023-10-04 10:22 UTC, alexanderby commented
<img width="792" alt="Screenshot 2023-10-04 at 11 20 44" src="https://github.com/ag-grid/ag-charts/assets/9638588/d3940ace-21c5-4b75-b74e-7dd44cbf3f51">
If it's linear easing, the shapes shouldn't grow over halp of the circle at 50%.