Focus box fixes
ag-grid/ag-charts pull request #3169
Opened 2024-12-06 13:54 UTC by jacobp100

2024-12-06 14:09 UTC, olegat requested changes
Great work Jacob! I think that adding the clipping logic to `FocusIndicator.updateBounds` seems like the good approach.

Key takeaways:
- It preferable to use `BBoxValues` and only use the `BBox` type when it is absolutely necessary
- Do not set the `display: none` CSS property if the focus indicator does not intersect with the hoverRect.
- The `ZoomManager.panToBBox` will still log an error if the focus indicator does not fit in the series area's bounds. Make sure to update that too.

2024-12-06 14:09 UTC, olegat commented on packages/ag-charts-community/src/chart/overlay/overlay.ts
> +    public focusBox?: BBox;
Keep this type as-is, or better yet change it to `BBoxValue`

2024-12-06 14:09 UTC, olegat commented on packages/ag-charts-community/src/dom/focusIndicator.ts
> +import { BBox } from '../integrated-charts-scene';
Caution with these imports

2024-12-06 14:09 UTC, olegat commented on packages/ag-charts-community/src/dom/focusIndicator.ts
> +            this.element.style.display = 'none';
Do not touch the `display` property. The WCAG success criteria requires the focus indicator to remain visible at all times for keyboard users. If the input `bounds` does not intersect with the `hoverRect`, then it's much better to draw a focus indicator with a height or width of 0 than to draw nothing at all.

2024-12-06 14:09 UTC, olegat commented on packages/ag-charts-community/src/dom/focusIndicator.ts
> +    updateBounds(bounds: Path | BBox | undefined, hoverRect?: BBox) {
Keep the inputs as `BBoxValues`.

2024-12-06 14:09 UTC, olegat commented on packages/ag-charts-community/src/scene/bbox.ts
> +    relativeClip(clipRect: BBox | undefined): this {
Move this `src/util/bboxinterface.ts`

2024-12-06 14:09 UTC, olegat commented on packages/ag-charts-community/src/dom/focusIndicator.ts
> +            setElementBBox(this.div, bounds.relativeClip(hoverRect));
Change this to `BBoxValues.relativeClip(bounds, hoverRect)` to avoid the unnecessary `BBox` type requirement.

2024-12-06 14:09 UTC, jacobp100 commented on packages/ag-charts-community/src/chart/overlay/overlay.ts
> +    public focusBox?: BBox;
It's needed to use the BBox methods

2024-12-06 14:28 UTC, olegat commented on packages/ag-charts-community/src/dom/focusIndicator.ts
> +        if (!boundsVisible) {
This condition is unnecessary. The `relativeClip` in the `else` clause will set the height or width to 0 if necessary.

The only advantage of this `if(!boundsVisible)` condition is that it also handle SVG-based focus indicators which currently has no clipping in production. But I would prefer to leave the SVG rendering logic unchanged, even if our current implementation is a bit buggy.

2024-12-09 09:55 UTC, alantreadway approved these changes
Verified locally, pushed snapshot updates.

2024-12-09 09:56 UTC, merged